# Generated by Django 3.0.3 on 2020-04-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.CharField(default='12', max_length=3, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('range', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('coordinates', models.FloatField()),
                ('timezone', models.TextField(default='Europe/Moscow')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_ref', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.DateField()),
                ('total_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=10, null=True)),
                ('scheduled_departure', models.DateTimeField(null=True)),
                ('scheduled_arrival', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('aircraft_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='airtrans.Aircraft')),
                ('arrival_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='airtrans.Airport')),
                ('departure_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='airtrans.Airport')),
            ],
            options={
                'unique_together': {('flight_no', 'scheduled_departure')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=50)),
                ('passenger_name', models.CharField(max_length=100)),
                ('contact_data', models.CharField(max_length=100)),
                ('book_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airtrans.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(max_length=30, null=True)),
                ('amount', models.PositiveIntegerField(verbose_name='ticket_price')),
                ('flight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flight')),
                ('ticket_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airtrans.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_no', models.CharField(default='1A', max_length=5, primary_key=True, serialize=False)),
                ('fare_conditions', models.CharField(max_length=30, null=True)),
                ('aircraft_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.PositiveIntegerField()),
                ('seat_no', models.CharField(max_length=5, null=True)),
                ('flight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flight')),
                ('ticket_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airtrans.Ticket')),
            ],
        ),
    ]
