# Generated by Django 3.0.3 on 2020-04-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_code',
            field=models.CharField(default='', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
    ]
